name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/enisimami/enisi_test:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/enisimami/enisi_test:latest
